from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QFont, QColor

class Ui_game(object):

    # I've changed the GUIs around a bit.  They are no londer resizable.  I've added a WOJ logo and the game board.
    # Still need a wheel.  This will be tricky to add all the names.  The grid layout needs to be adjusted to the
    # correct position and font needs to change.  The other text data can move too.
    def setupUi(self, game):
        game.setObjectName("game")
        game.setFixedSize(1150, 750)
        #sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        #sizePolicy.setHorizontalStretch(6)
        #sizePolicy.setVerticalStretch(6)
        #sizePolicy.setHeightForWidth(game.sizePolicy().hasHeightForWidth())
        #game.setSizePolicy(sizePolicy)
        self.logo = QtWidgets.QLabel(game)
        self.logo.setGeometry(QtCore.QRect(150, 15, 1000, 100))
        self.logo.setPixmap(QtGui.QPixmap('WOJlogo.png'))
        self.logo.setObjectName("logo")

        self.board = QtWidgets.QLabel(game)
        self.board.setGeometry(QtCore.QRect(475, 75, 650, 650))
        self.board.setPixmap(QtGui.QPixmap('jeopardy.png'))
        self.board.setObjectName("board")

        self.round = QtWidgets.QLabel(game)
        self.round.setGeometry(QtCore.QRect(700, 120, 100, 30))
        self.round.setObjectName("round")
        self.spins = QtWidgets.QLabel(game)
        self.spins.setGeometry(QtCore.QRect(800, 120, 100, 30))
        self.spins.setObjectName("spins")
        self.contestant1 = QtWidgets.QLabel(game)
        self.contestant1.setGeometry(QtCore.QRect(100, 700, 200, 30))
        self.contestant1.setObjectName("contestant1")
        self.contestant2 = QtWidgets.QLabel(game)
        self.contestant2.setGeometry(QtCore.QRect(340, 700, 200, 30))
        self.contestant2.setObjectName("contestant2")
        self.contestant3 = QtWidgets.QLabel(game)
        self.contestant3.setGeometry(QtCore.QRect(650, 700, 200, 30))
        self.contestant3.setObjectName("contestant3")
        self.spinner = QtWidgets.QPushButton(game)
        self.spinner.setGeometry(QtCore.QRect(60, 340, 112, 34))
        self.spinner.setObjectName("spinner")
        self.sector = QtWidgets.QLabel(game)
        self.sector.setGeometry(QtCore.QRect(70, 250, 121, 51))
        self.sector.setObjectName("sector")

        self.gridLayoutWidget = QtWidgets.QWidget(game)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(500, 160, 600, 500))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.c2q2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c2q2.setAlignment(QtCore.Qt.AlignCenter)
        self.c2q2.setObjectName("c2q2")
        self.gridLayout.addWidget(self.c2q2, 2, 1, 1, 1)
        self.c5q3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c5q3.setAlignment(QtCore.Qt.AlignCenter)
        self.c5q3.setObjectName("c5q3")
        self.gridLayout.addWidget(self.c5q3, 3, 4, 1, 1)
        self.c4q3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c4q3.setAlignment(QtCore.Qt.AlignCenter)
        self.c4q3.setObjectName("c4q3")
        self.gridLayout.addWidget(self.c4q3, 3, 3, 1, 1)
        self.c1q4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c1q4.setAlignment(QtCore.Qt.AlignCenter)
        self.c1q4.setObjectName("c1q4")
        self.gridLayout.addWidget(self.c1q4, 4, 0, 1, 1)
        self.c5q2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c5q2.setAlignment(QtCore.Qt.AlignCenter)
        self.c5q2.setObjectName("c5q2")
        self.gridLayout.addWidget(self.c5q2, 2, 4, 1, 1)
        self.c3q2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c3q2.setAlignment(QtCore.Qt.AlignCenter)
        self.c3q2.setObjectName("c3q2")
        self.gridLayout.addWidget(self.c3q2, 2, 2, 1, 1)
        self.c1q1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c1q1.setAlignment(QtCore.Qt.AlignCenter)
        self.c1q1.setObjectName("c1q1")
        self.gridLayout.addWidget(self.c1q1, 1, 0, 1, 1)
        self.c2q5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c2q5.setAlignment(QtCore.Qt.AlignCenter)
        self.c2q5.setObjectName("c2q5")
        self.gridLayout.addWidget(self.c2q5, 5, 1, 1, 1)
        self.c4q4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c4q4.setAlignment(QtCore.Qt.AlignCenter)
        self.c4q4.setObjectName("c4q4")
        self.gridLayout.addWidget(self.c4q4, 4, 3, 1, 1)
        self.c2q1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c2q1.setAlignment(QtCore.Qt.AlignCenter)
        self.c2q1.setObjectName("c2q1")
        self.gridLayout.addWidget(self.c2q1, 1, 1, 1, 1)
        self.c2q4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c2q4.setAlignment(QtCore.Qt.AlignCenter)
        self.c2q4.setObjectName("c2q4")
        self.gridLayout.addWidget(self.c2q4, 4, 1, 1, 1)
        self.c1q5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c1q5.setAlignment(QtCore.Qt.AlignCenter)
        self.c1q5.setObjectName("c1q5")
        self.gridLayout.addWidget(self.c1q5, 5, 0, 1, 1)
        self.c4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c4.setAlignment(QtCore.Qt.AlignCenter)
        self.c4.setObjectName("c4")
        self.gridLayout.addWidget(self.c4, 0, 3, 1, 1)
        self.c3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c3.setAlignment(QtCore.Qt.AlignCenter)
        self.c3.setObjectName("c3")
        self.gridLayout.addWidget(self.c3, 0, 2, 1, 1)
        self.c2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c2.setAlignment(QtCore.Qt.AlignCenter)
        self.c2.setObjectName("c2")
        self.gridLayout.addWidget(self.c2, 0, 1, 1, 1)
        self.c6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c6.setAlignment(QtCore.Qt.AlignCenter)
        self.c6.setObjectName("c6")
        self.gridLayout.addWidget(self.c6, 0, 5, 1, 1)
        self.c5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c5.setAlignment(QtCore.Qt.AlignCenter)
        self.c5.setObjectName("c5")
        self.gridLayout.addWidget(self.c5, 0, 4, 1, 1)
        self.c1q3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c1q3.setAlignment(QtCore.Qt.AlignCenter)
        self.c1q3.setObjectName("c1q3")
        self.gridLayout.addWidget(self.c1q3, 3, 0, 1, 1)
        self.c5q1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c5q1.setAlignment(QtCore.Qt.AlignCenter)
        self.c5q1.setObjectName("c5q1")
        self.gridLayout.addWidget(self.c5q1, 1, 4, 1, 1)
        self.c2q3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c2q3.setAlignment(QtCore.Qt.AlignCenter)
        self.c2q3.setObjectName("c2q3")
        self.gridLayout.addWidget(self.c2q3, 3, 1, 1, 1)
        self.c3q3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c3q3.setAlignment(QtCore.Qt.AlignCenter)
        self.c3q3.setObjectName("c3q3")
        self.gridLayout.addWidget(self.c3q3, 3, 2, 1, 1)
        self.c4q1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c4q1.setAlignment(QtCore.Qt.AlignCenter)
        self.c4q1.setObjectName("c4q1")
        self.gridLayout.addWidget(self.c4q1, 1, 3, 1, 1)
        self.c6q2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c6q2.setAlignment(QtCore.Qt.AlignCenter)
        self.c6q2.setObjectName("c6q2")
        self.gridLayout.addWidget(self.c6q2, 2, 5, 1, 1)
        self.c6q1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c6q1.setAlignment(QtCore.Qt.AlignCenter)
        self.c6q1.setObjectName("c6q1")
        self.gridLayout.addWidget(self.c6q1, 1, 5, 1, 1)
        self.c3q4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c3q4.setAlignment(QtCore.Qt.AlignCenter)
        self.c3q4.setObjectName("c3q4")
        self.gridLayout.addWidget(self.c3q4, 4, 2, 1, 1)
        self.c3q1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c3q1.setAlignment(QtCore.Qt.AlignCenter)
        self.c3q1.setObjectName("c3q1")
        self.gridLayout.addWidget(self.c3q1, 1, 2, 1, 1)
        self.c1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c1.setAlignment(QtCore.Qt.AlignCenter)
        self.c1.setObjectName("c1")
        self.gridLayout.addWidget(self.c1, 0, 0, 1, 1)
        self.c6q3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c6q3.setAlignment(QtCore.Qt.AlignCenter)
        self.c6q3.setObjectName("c6q3")
        self.gridLayout.addWidget(self.c6q3, 3, 5, 1, 1)
        self.c4q2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c4q2.setAlignment(QtCore.Qt.AlignCenter)
        self.c4q2.setObjectName("c4q2")
        self.gridLayout.addWidget(self.c4q2, 2, 3, 1, 1)
        self.c1q2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c1q2.setAlignment(QtCore.Qt.AlignCenter)
        self.c1q2.setObjectName("c1q2")
        self.gridLayout.addWidget(self.c1q2, 2, 0, 1, 1)
        self.c5q4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c5q4.setAlignment(QtCore.Qt.AlignCenter)
        self.c5q4.setObjectName("c5q4")
        self.gridLayout.addWidget(self.c5q4, 4, 4, 1, 1)
        self.c6q4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c6q4.setAlignment(QtCore.Qt.AlignCenter)
        self.c6q4.setObjectName("c6q4")
        self.gridLayout.addWidget(self.c6q4, 4, 5, 1, 1)
        self.c3q5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c3q5.setAlignment(QtCore.Qt.AlignCenter)
        self.c3q5.setObjectName("c3q5")
        self.gridLayout.addWidget(self.c3q5, 5, 2, 1, 1)
        self.c5q5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c5q5.setAlignment(QtCore.Qt.AlignCenter)
        self.c5q5.setObjectName("c5q5")
        self.gridLayout.addWidget(self.c5q5, 5, 4, 1, 1)
        self.c4q5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c4q5.setAlignment(QtCore.Qt.AlignCenter)
        self.c4q5.setObjectName("c4q5")
        self.gridLayout.addWidget(self.c4q5, 5, 3, 1, 1)
        self.c6q5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c6q5.setAlignment(QtCore.Qt.AlignCenter)
        self.c6q5.setObjectName("c6q5")
        self.gridLayout.addWidget(self.c6q5, 5, 5, 1, 1)

        self.back = QtWidgets.QPushButton(game)
        self.back.setGeometry(QtCore.QRect(700, 650, 200, 70))
        self.back.setObjectName("back")

        self.retranslateUi(game)
        QtCore.QMetaObject.connectSlotsByName(game)

    def retranslateUi(self, game):
        _translate = QtCore.QCoreApplication.translate
        game.setWindowTitle(_translate("game", "Wheel of Jeopardy"))
        font = QFont()
        color = QColor(239, 167, 53)
        self.round.setText(_translate("game", "Round:"))
        self.spins.setText(_translate("game", "Spins:"))
        self.contestant1.setText(_translate("game", "Contestant 1:"))
        self.contestant2.setText(_translate("game", "Contestant 2:"))
        self.contestant3.setText(_translate("game", "Contestant 3:"))
        self.spinner.setText(_translate("game", "Spin!"))
        self.sector.setText(_translate("game", "Selected Sector"))
        self.c2q2.setText(_translate("game", "$400"))
        self.c5q3.setText(_translate("game", "$600"))
        self.c4q3.setText(_translate("game", "$600"))
        self.c1q4.setText(_translate("game", "$800"))
        self.c5q2.setText(_translate("game", "$400"))
        self.c3q2.setText(_translate("game", "$400"))
        self.c1q1.setText(_translate("game", "$200"))
        self.c2q5.setText(_translate("game", "$1,000"))
        self.c4q4.setText(_translate("game", "$800"))
        self.c2q1.setText(_translate("game", "$200"))
        self.c2q4.setText(_translate("game", "$800"))
        self.c1q5.setText(_translate("game", "$1,000"))
        self.c4.setText(_translate("game", "Category 4"))
        self.c3.setText(_translate("game", "Category 3"))
        self.c2.setText(_translate("game", "Category 2"))
        self.c6.setText(_translate("game", "Category 6"))
        self.c5.setText(_translate("game", "Category 5"))
        self.c1q3.setText(_translate("game", "$600"))
        self.c5q1.setText(_translate("game", "$200"))
        self.c2q3.setText(_translate("game", "$600"))
        self.c3q3.setText(_translate("game", "$600"))
        self.c4q1.setText(_translate("game", "$200"))
        self.c6q2.setText(_translate("game", "$400"))
        self.c6q1.setText(_translate("game", "$200"))
        self.c3q4.setText(_translate("game", "$800"))
        self.c3q1.setText(_translate("game", "$200"))
        self.c1.setText(_translate("game", "Category 1"))
        self.c6q3.setText(_translate("game", "$600"))
        self.c4q2.setText(_translate("game", "$400"))
        self.c1q2.setText(_translate("game", "$400"))
        self.c5q4.setText(_translate("game", "$800"))
        self.c6q4.setText(_translate("game", "$800"))
        self.c3q5.setText(_translate("game", "$1,000"))
        self.c5q5.setText(_translate("game", "$1,000"))
        self.c4q5.setText(_translate("game", "$1,000"))
        self.c6q5.setText(_translate("game", "$1,000"))
        self.back.setText(_translate("game", "Back to Main Menu"))
