# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/game.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_game(object):
    def setupUi(self, game):
        game.setObjectName("game")
        game.resize(953, 750)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(game.sizePolicy().hasHeightForWidth())
        game.setSizePolicy(sizePolicy)
        self.title = QtWidgets.QTextEdit(game)
        self.title.setGeometry(QtCore.QRect(290, 20, 401, 51))
        self.title.setObjectName("title")
        self.round = QtWidgets.QLabel(game)
        self.round.setGeometry(QtCore.QRect(740, 30, 151, 51))
        self.round.setObjectName("round")
        self.spins = QtWidgets.QLabel(game)
        self.spins.setGeometry(QtCore.QRect(740, 70, 151, 51))
        self.spins.setObjectName("spins")
        self.contestant1 = QtWidgets.QLabel(game)
        self.contestant1.setGeometry(QtCore.QRect(100, 580, 151, 51))
        self.contestant1.setObjectName("contestant1")
        self.contestant2 = QtWidgets.QLabel(game)
        self.contestant2.setGeometry(QtCore.QRect(340, 580, 151, 51))
        self.contestant2.setObjectName("contestant2")
        self.contestant3 = QtWidgets.QLabel(game)
        self.contestant3.setGeometry(QtCore.QRect(650, 580, 151, 51))
        self.contestant3.setObjectName("contestant3")
        self.spinner = QtWidgets.QPushButton(game)
        self.spinner.setGeometry(QtCore.QRect(60, 340, 112, 34))
        self.spinner.setObjectName("spinner")
        self.sector = QtWidgets.QLabel(game)
        self.sector.setGeometry(QtCore.QRect(70, 250, 121, 51))
        self.sector.setObjectName("sector")
        self.gridLayoutWidget = QtWidgets.QWidget(game)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(270, 140, 651, 431))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.c2q2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c2q2.setAlignment(QtCore.Qt.AlignCenter)
        self.c2q2.setObjectName("c2q2")
        self.gridLayout.addWidget(self.c2q2, 2, 1, 1, 1)
        self.c5q3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c5q3.setAlignment(QtCore.Qt.AlignCenter)
        self.c5q3.setObjectName("c5q3")
        self.gridLayout.addWidget(self.c5q3, 3, 4, 1, 1)
        self.c4q3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c4q3.setAlignment(QtCore.Qt.AlignCenter)
        self.c4q3.setObjectName("c4q3")
        self.gridLayout.addWidget(self.c4q3, 3, 3, 1, 1)
        self.c1q4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c1q4.setAlignment(QtCore.Qt.AlignCenter)
        self.c1q4.setObjectName("c1q4")
        self.gridLayout.addWidget(self.c1q4, 4, 0, 1, 1)
        self.c5q2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c5q2.setAlignment(QtCore.Qt.AlignCenter)
        self.c5q2.setObjectName("c5q2")
        self.gridLayout.addWidget(self.c5q2, 2, 4, 1, 1)
        self.c3q2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c3q2.setAlignment(QtCore.Qt.AlignCenter)
        self.c3q2.setObjectName("c3q2")
        self.gridLayout.addWidget(self.c3q2, 2, 2, 1, 1)
        self.c1q1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c1q1.setAlignment(QtCore.Qt.AlignCenter)
        self.c1q1.setObjectName("c1q1")
        self.gridLayout.addWidget(self.c1q1, 1, 0, 1, 1)
        self.c2q5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c2q5.setAlignment(QtCore.Qt.AlignCenter)
        self.c2q5.setObjectName("c2q5")
        self.gridLayout.addWidget(self.c2q5, 5, 1, 1, 1)
        self.c4q4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c4q4.setAlignment(QtCore.Qt.AlignCenter)
        self.c4q4.setObjectName("c4q4")
        self.gridLayout.addWidget(self.c4q4, 4, 3, 1, 1)
        self.c2q1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c2q1.setAlignment(QtCore.Qt.AlignCenter)
        self.c2q1.setObjectName("c2q1")
        self.gridLayout.addWidget(self.c2q1, 1, 1, 1, 1)
        self.c2q4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c2q4.setAlignment(QtCore.Qt.AlignCenter)
        self.c2q4.setObjectName("c2q4")
        self.gridLayout.addWidget(self.c2q4, 4, 1, 1, 1)
        self.c1q5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c1q5.setAlignment(QtCore.Qt.AlignCenter)
        self.c1q5.setObjectName("c1q5")
        self.gridLayout.addWidget(self.c1q5, 5, 0, 1, 1)
        self.c4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c4.setAlignment(QtCore.Qt.AlignCenter)
        self.c4.setObjectName("c4")
        self.gridLayout.addWidget(self.c4, 0, 3, 1, 1)
        self.c3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c3.setAlignment(QtCore.Qt.AlignCenter)
        self.c3.setObjectName("c3")
        self.gridLayout.addWidget(self.c3, 0, 2, 1, 1)
        self.c2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c2.setAlignment(QtCore.Qt.AlignCenter)
        self.c2.setObjectName("c2")
        self.gridLayout.addWidget(self.c2, 0, 1, 1, 1)
        self.c6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c6.setAlignment(QtCore.Qt.AlignCenter)
        self.c6.setObjectName("c6")
        self.gridLayout.addWidget(self.c6, 0, 5, 1, 1)
        self.c5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c5.setAlignment(QtCore.Qt.AlignCenter)
        self.c5.setObjectName("c5")
        self.gridLayout.addWidget(self.c5, 0, 4, 1, 1)
        self.c1q3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c1q3.setAlignment(QtCore.Qt.AlignCenter)
        self.c1q3.setObjectName("c1q3")
        self.gridLayout.addWidget(self.c1q3, 3, 0, 1, 1)
        self.c5q1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c5q1.setAlignment(QtCore.Qt.AlignCenter)
        self.c5q1.setObjectName("c5q1")
        self.gridLayout.addWidget(self.c5q1, 1, 4, 1, 1)
        self.c2q3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c2q3.setAlignment(QtCore.Qt.AlignCenter)
        self.c2q3.setObjectName("c2q3")
        self.gridLayout.addWidget(self.c2q3, 3, 1, 1, 1)
        self.c3q3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c3q3.setAlignment(QtCore.Qt.AlignCenter)
        self.c3q3.setObjectName("c3q3")
        self.gridLayout.addWidget(self.c3q3, 3, 2, 1, 1)
        self.c4q1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c4q1.setAlignment(QtCore.Qt.AlignCenter)
        self.c4q1.setObjectName("c4q1")
        self.gridLayout.addWidget(self.c4q1, 1, 3, 1, 1)
        self.c6q2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c6q2.setAlignment(QtCore.Qt.AlignCenter)
        self.c6q2.setObjectName("c6q2")
        self.gridLayout.addWidget(self.c6q2, 2, 5, 1, 1)
        self.c6q1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c6q1.setAlignment(QtCore.Qt.AlignCenter)
        self.c6q1.setObjectName("c6q1")
        self.gridLayout.addWidget(self.c6q1, 1, 5, 1, 1)
        self.c3q4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c3q4.setAlignment(QtCore.Qt.AlignCenter)
        self.c3q4.setObjectName("c3q4")
        self.gridLayout.addWidget(self.c3q4, 4, 2, 1, 1)
        self.c3q1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c3q1.setAlignment(QtCore.Qt.AlignCenter)
        self.c3q1.setObjectName("c3q1")
        self.gridLayout.addWidget(self.c3q1, 1, 2, 1, 1)
        self.c1 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c1.setAlignment(QtCore.Qt.AlignCenter)
        self.c1.setObjectName("c1")
        self.gridLayout.addWidget(self.c1, 0, 0, 1, 1)
        self.c6q3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c6q3.setAlignment(QtCore.Qt.AlignCenter)
        self.c6q3.setObjectName("c6q3")
        self.gridLayout.addWidget(self.c6q3, 3, 5, 1, 1)
        self.c4q2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c4q2.setAlignment(QtCore.Qt.AlignCenter)
        self.c4q2.setObjectName("c4q2")
        self.gridLayout.addWidget(self.c4q2, 2, 3, 1, 1)
        self.c1q2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c1q2.setAlignment(QtCore.Qt.AlignCenter)
        self.c1q2.setObjectName("c1q2")
        self.gridLayout.addWidget(self.c1q2, 2, 0, 1, 1)
        self.c5q4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c5q4.setAlignment(QtCore.Qt.AlignCenter)
        self.c5q4.setObjectName("c5q4")
        self.gridLayout.addWidget(self.c5q4, 4, 4, 1, 1)
        self.c6q4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c6q4.setAlignment(QtCore.Qt.AlignCenter)
        self.c6q4.setObjectName("c6q4")
        self.gridLayout.addWidget(self.c6q4, 4, 5, 1, 1)
        self.c3q5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c3q5.setAlignment(QtCore.Qt.AlignCenter)
        self.c3q5.setObjectName("c3q5")
        self.gridLayout.addWidget(self.c3q5, 5, 2, 1, 1)
        self.c5q5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c5q5.setAlignment(QtCore.Qt.AlignCenter)
        self.c5q5.setObjectName("c5q5")
        self.gridLayout.addWidget(self.c5q5, 5, 4, 1, 1)
        self.c4q5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c4q5.setAlignment(QtCore.Qt.AlignCenter)
        self.c4q5.setObjectName("c4q5")
        self.gridLayout.addWidget(self.c4q5, 5, 3, 1, 1)
        self.c6q5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.c6q5.setAlignment(QtCore.Qt.AlignCenter)
        self.c6q5.setObjectName("c6q5")
        self.gridLayout.addWidget(self.c6q5, 5, 5, 1, 1)
        self.back = QtWidgets.QPushButton(game)
        self.back.setGeometry(QtCore.QRect(730, 670, 181, 61))
        self.back.setObjectName("back")

        self.retranslateUi(game)
        QtCore.QMetaObject.connectSlotsByName(game)

    def retranslateUi(self, game):
        _translate = QtCore.QCoreApplication.translate
        game.setWindowTitle(_translate("game", "Form"))
        self.title.setHtml(_translate("game", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">Wheel of Jeopardy</span></p></body></html>"))
        self.round.setText(_translate("game", "Round:"))
        self.spins.setText(_translate("game", "Spins:"))
        self.contestant1.setText(_translate("game", "Contestant 1:"))
        self.contestant2.setText(_translate("game", "Contestant 2:"))
        self.contestant3.setText(_translate("game", "Contestant 3:"))
        self.spinner.setText(_translate("game", "Spin!"))
        self.sector.setText(_translate("game", "Selected Sector"))
        self.c2q2.setText(_translate("game", "$400"))
        self.c5q3.setText(_translate("game", "$600"))
        self.c4q3.setText(_translate("game", "$600"))
        self.c1q4.setText(_translate("game", "$800"))
        self.c5q2.setText(_translate("game", "$400"))
        self.c3q2.setText(_translate("game", "$400"))
        self.c1q1.setText(_translate("game", "$200"))
        self.c2q5.setText(_translate("game", "$1,000"))
        self.c4q4.setText(_translate("game", "$800"))
        self.c2q1.setText(_translate("game", "$200"))
        self.c2q4.setText(_translate("game", "$800"))
        self.c1q5.setText(_translate("game", "$1,000"))
        self.c4.setText(_translate("game", "Category 4"))
        self.c3.setText(_translate("game", "Category 3"))
        self.c2.setText(_translate("game", "Category 2"))
        self.c6.setText(_translate("game", "Category 6"))
        self.c5.setText(_translate("game", "Category 5"))
        self.c1q3.setText(_translate("game", "$600"))
        self.c5q1.setText(_translate("game", "$200"))
        self.c2q3.setText(_translate("game", "$600"))
        self.c3q3.setText(_translate("game", "$600"))
        self.c4q1.setText(_translate("game", "$200"))
        self.c6q2.setText(_translate("game", "$400"))
        self.c6q1.setText(_translate("game", "$200"))
        self.c3q4.setText(_translate("game", "$800"))
        self.c3q1.setText(_translate("game", "$200"))
        self.c1.setText(_translate("game", "Category 1"))
        self.c6q3.setText(_translate("game", "$600"))
        self.c4q2.setText(_translate("game", "$400"))
        self.c1q2.setText(_translate("game", "$400"))
        self.c5q4.setText(_translate("game", "$800"))
        self.c6q4.setText(_translate("game", "$800"))
        self.c3q5.setText(_translate("game", "$1,000"))
        self.c5q5.setText(_translate("game", "$1,000"))
        self.c4q5.setText(_translate("game", "$1,000"))
        self.c6q5.setText(_translate("game", "$1,000"))
        self.back.setText(_translate("game", "Back to Main Menu"))

